### ISSUE TITLE
Hunter aimed shot issue

### ISSUE THREAD

**Issue by siweia** [rgd87/LibClassicCasterino#14]
When unit is "player" itself, CastingInfo return nil for Aimed shot.
And the castbar stay hidden because of that.
Other units working great.
I did a quick fix atm: https://paste.ubuntu.com/p/2mzbc4jkWs/

**Comment by d87** [comment]
Well it's not a bug, Aimed Shot just doesn't have a normal player castbar when you cast it, so that's why CastingInfo is nil. It can be tracked from combat log for enemies tho and the lib does that, because it can.

I don't see how your quick fix would work, because UnitCastingInfo also needs to be temporarily rerouted from CastingInfo for aimed shot
Right now I'm kinda tired of drycoding every random special case for classes i don't have.
So maybe later

**Comment by siweia** [comment]
Sorry about the paste bin.
It might be easier to see at here[https://github.com/siweia/NDuiClassic/commit/3c48722df13b1bf919ce5f837c151fafb1a66f75](url)

**Comment by d87** [comment]
Ok, please test this https://github.com/rgd87/LibClassicCasterino/commit/3b8ec3d8be018b2f5cb6fb15f154557b0a496194

**Comment by siweia** [comment]
It works great now, thx.
